---
title: "Tarea 2-estadisticas policiales 2021"
author: "Yeimy Navarroo Segura"
date: '2022-06-22'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tarea 2
## Carga de paquetes
```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)
library(DT)
library(readxl)
library(graphics)
library(stats)
```

## Tabla Dt
```{r carga del excel}
estadisticas_policiales <-
  read_excel("C:/Users/Dell/Documents/I-2022/Procesamiento de Datos Geograficos/Tarea 2/estadisticaspoliciales2021.xls")
```

## Curación de datos
```{r cambiar fechas}
estadisticas_policiales$Fecha <- as.Date(estadisticas_policiales$Fecha, format = "%d/%m/%Y")
```

## Transformación
```{r transformación de datos}
estadisticas_policiales <-
  estadisticas_policiales %>%
  select(Delito, Fecha, "Víctima" = Victima, Edad, "Género" = Genero, Provincia, "Cantón" = Canton ) %>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y"))
```

## Visualización en forma tabular
```{r}
estadisticas_policiales %>%
  datatable(options = list(
    pageLength = 10,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```

## Graficos
### Gráfico de barras 1
```{r}
ggplot2_cantidad_delitos <-
  estadisticas_policiales %>%
  count(Delito) %>% 
  ggplot(aes(x = reorder(Delito, n), y = n)) +
  geom_bar(stat = "identity") +
  ggtitle("Gráfico cantidad de delitos por tipo de delito") +
  xlab("Delito") +
  ylab("Cantidad de Delitos") +
  theme_get()
  
ggplotly(ggplot2_cantidad_delitos) %>% config(locale = 'es')
```

### Gráfico de barras 2

```{r}
estadisticas_policiales <-
  estadisticas_policiales %>%
  mutate(mes = format(Fecha, "%B")) %>%
  select(Delito, Fecha, Víctima, Edad, Género, Provincia, Cantón, mes) %>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y"))

ggplot2_cantidad_delitos_mes <-
  estadisticas_policiales %>% 
  ggplot(aes(x = mes)) +
  geom_bar() +
  ggtitle("Cantidad de delitos por mes") +
  xlab("Mes") +
  ylab("Cantidad de Delitos") +
  theme_get() 

ggplotly(ggplot2_cantidad_delitos_mes) %>% config(locale = 'es')
```

### Gráfico de barras 3
```{r Gráfico barras apiladas}
ggplot2_delito_genero <-
  estadisticas_policiales %>%
  ggplot(aes(x = Delito, fill = Género)) +
  geom_bar(position = "fill") +
  ggtitle("Gráfico de tipo de delitos por género") +
  xlab("proporción de delito por Genéro") +
  ylab("Delito") +
  labs(fill = "Género") +
  theme_get()

ggplotly(ggplot2_delito_genero) %>% config(locale = 'es')
```

### Gráfico de barras 4
```{r}
estadisticas_policiales <-
  filter(estadisticas_policiales,
         grepl('HEREDIA|ALAJUELA|CARTAGO|SAN JOSE', Cantón))
  
  
ggplot2_delitos_canton <-
  ggplot(data = estadisticas_policiales, aes(x = Cantón)) +
  geom_bar() +
  ggtitle("Gráfico de la cantidad de delitos por canton") +
  xlab("Cantones") +
  ylab("Cantidad de Delitos") +
  theme_get()

ggplotly(ggplot2_delitos_canton) %>% config(locale = 'es')
```
  
  

